# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
